### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by meganrm** [allen-cell-animated/cell-catalog#16]
- [x] remove hover from row 
- [x] remove hover from parental line button 
- [ ] reduce animation time 
- [x] always wrap the snp at the colon 
- [x] get rid of semi colon, always have them stacked 
- [x] semi bold the numbers on the 
- [x] change .disease-catalog-module--banner-content--394e1 to font weight 300 
- [x] add dividing line on chart
- [x] fix border radius on blue chart line 
- [ ] #25
- [x] SNP for AICS-104 is incorrect. It should be: NM_000257.4(MYH7):c.752C>A(p.His251Asn)
- [x] AICS-104 should have 2 isogenic controls instead of 1
- [x] All Gene Names should be all lower case (e.g. myosin heavy chain 7) for consistency with current cell catalog
- [ ] On some of the parental line buttons it looks like the bottom of the info icon is cut off slightly (can't tell if this is just my screen or not)
- [ ] #26
- [x] Ensure collaborator labs are in italics
- [x] In the very bottom WTC-11 blurb, Genomics should be a hyperlink to: https://www.allencell.org/genomics.html
- [x] Parental Line Modals: make labels (gene symbol, etc.) font size 18. Make content (LMNB1, etc.) font size 16. Make "More Information" font size 16 and semi bolded. 
- [x] In each disease table, the column header and each cell line item should be inset 32pt from the left instead of 16pt. Only the table title (Cardiomyopathy, etc.) should be inset 16pt

**Comment by meganrm** [comment]
@TravisKroeker when [this PR ](https://github.com/allen-cell-animated/cell-catalog/pull/19) finishes building there will be a link to see a working preview

**Comment by meganrm** [comment]
@TravisKroeker [most recent version](https://deploy-preview-24--cell-catalog.netlify.app/disease-catalog/), which should include all the changes that I've checked off on this issue

**Comment by TravisKroeker** [comment]
@meganrm These changes look great! A couple notes on the parental line modals:
- "More Info" button text still looks tiny. Bump it up to 16pt and semibold it. 
- The changes to the font size in the body of the modal (which look much better) are causing it to wrap. Let's bump up the width of the modal slightly so that it's on a single line. Eventually we might have some gene names that are extraordinarily long and will need to wrap, but not for a couple years if ever. 

I might have a few more comments once the obtain cell line and cert. of analysis features are put in place but the rest is soooooo clean.

**Comment by meganrm** [comment]
@TravisKroeker [this link](https://deploy-preview-24--cell-catalog.netlify.app/disease-catalog/)  has been updated with the two additional tweaks on the parental line modal

**Comment by TravisKroeker** [comment]
Love it. Noticed you made changes to the icon hover state too to match the text. Good catch.
